language: node_js
sudo: false
node_js:
  - '4.4.7'


cache:
directories:
  - node_modules
  - bower_components

branches:
  only: ["master"]


before_install:
- sudo apt-get update -q

script: npm install && bower install
