language: node_js
sudo: false
node_js:
  - '4.4.7'


cache:
directories:
  - node_modules
  - bower_components

branches:
  only: ["master"]


script:
  - npm install -g bower grunt
  - bower install 
  - grunt build
